name: CI/CD Pipeline

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

on:
  pull_request:
  push:
    branches:
      - main
      - alpha
      - beta
      - canary
      - pre/rc

jobs:
  lint:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.lint.yml@main
    secrets: inherit

  test:
    needs: lint
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.test.yml@main
    secrets: inherit

  release:
    needs: test
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.release.yml@main
    secrets: inherit
    with:
      branch_name: ${{ github.ref_name }}
